# Generated by Django 4.2.28 on 2026-02-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(db_index=True, help_text='Media ID from Instagram Graph API.', max_length=255, unique=True)),
                ('caption', models.TextField(blank=True, default='')),
                ('media_type', models.CharField(blank=True, default='', help_text='Type of media: IMAGE, VIDEO, CAROUSEL_ALBUM.', max_length=50)),
                ('media_url', models.URLField(blank=True, default='', max_length=1024)),
                ('permalink', models.URLField(blank=True, default='', max_length=1024)),
                ('timestamp', models.DateTimeField(blank=True, help_text='Original publish timestamp from Instagram.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(db_index=True, help_text='Comment ID returned by Instagram Graph API.', max_length=255, unique=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instagram_app.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
